apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: frontendapp-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontendapp
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 20
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: couponapp-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: couponapp
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 20
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: discountapp-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: discountapp
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 20
---  
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: memberapp-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: memberapp
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 20  
  
